name: Nextcloud app store
description: Get metadata of the latest version of an app from Nextcloud app store

inputs:
  appid:
    description: Nextcloud app id
    required: true
  server_major:
    description: Nextcloud server major version number (optional)
    required: false
    default: ''

outputs:
  release:
    description: Metadata of the latest app release compatible with specified Nextcloud version
  version:
    description: Version of the release
  download:
    description: Download URL of the release tarball

runs:
  using: node20
  main: dist/index.js
